### PR TITLE
Reconnect if request fails with an I/O error

### LINKED ISSUE #62: Handle timeouts, reconnect
I think we should handle reconnecting in case of a timeout. Perhaps we can send `hello` on a timer to check the connection status: https://datatracker.ietf.org/doc/html/rfc5730#section-2.3

### PR DESCRIPTION
**Pull request by djc**
Fixes #62 in a relatively simple way.

### CODE REVIEW

File: src/client.rs [hunk 1]
```diff
@@ -149,21 +114,22 @@ impl<IO: AsyncRead + AsyncWrite + Unpin> EppClient<IO> {
...
     {
         let data = data.into();
-        let epp_xml = <C as Transaction<E>>::serialize_request(data.command, data.extension, id)?;
+        let epp_xml =
+            <Cmd as Transaction<Ext>>::serialize_request(data.command, data.extension, id)?;
 
         let response = self.connection.transact(&epp_xml).await?;
 
-        C::deserialize_response(&response)
+        Cmd::deserialize_response(&response)
```
Comment (nrempel) [inline src/client.rs:132]: These changes are just for clarity right?

**Review by nrempel — APPROVED** [review]

File: src/client.rs (hunk 1 above)
Comment (djc) [reply src/client.rs:132]: There's a conflict with the `C` type argument that's now the `Connector`, so I had to rename the `C` for `Command`.

File: src/connection.rs [hunk 2]
```diff
@@ -91,7 +94,17 @@ impl<IO: AsyncRead + AsyncWrite + Unpin> EppConnection<IO> {
     /// receieved to the request
     pub(crate) async fn transact(&mut self, content: &str) -> Result<String, Error> {
         debug!("{}: request: {}", self.registry, content);
-        self.send_epp_request(content).await?;
+
+        match self.send_epp_request(content).await {
+            Ok(()) => {}
+            Err(Error::Io(_)) => {
+                self.stream = self.connector.connect(self.timeout).await?;
+                self.send_epp_request(content).await?;
```
Comment (nrempel) [inline src/connection.rs:102]: Testing this, I think we actually need:

```suggestion
                self.stream = self.connector.connect(self.timeout).await?;
                self.greeting = self.get_epp_response().await?;
                self.send_epp_request(content).await?;
```

to pull the new greeting off the wire

**Review by nrempel — CHANGES_REQUESTED** [review]
